import { Helmet } from 'react-helmet-async'
import { Hero } from '../components/layout/Hero'
import { Section } from '../components/layout/Section'
import { CTABlock } from '../components/layout/CTABlock'
import { FAQ } from '../components/shared/FAQ'
import { SKOOL_URL } from '../data/site-config'

const COACHING_FAQ = [
  {
    q: 'Is there a free consultation or discovery call?',
    a: 'No. Your application captures your health history and goals. No call needed before you decide. The price and the process are both right here on this page. If you want to apply, apply. If you want to learn more first, join the free community and go through the courses.',
  },
  {
    q: 'What if I just want fitness coaching without the clinical side?',
    a: 'This is health optimization coaching. Training is one component alongside labs, clinical protocols, and ongoing bloodwork analysis. If you just want structured programming without the clinical oversight, check out our Programs page -- self-guided programs at $50 each through TrainHeroic.',
  },
  {
    q: 'What about prescriptions (TRT, HRT, peptides)?',
    a: 'If your clinical review determines you would benefit from prescriptions, we facilitate a doctor referral. Prescriptions are separate billing through the medical provider. We coordinate the process and your coaching team integrates the prescription protocol into your overall plan. You decide what you want to use -- we recommend based on your data.',
  },
  {
    q: 'What happens after 6 months?',
    a: 'Monthly continuation at $750/mo. Same team, same level of service, ongoing optimization. Quarterly labs continue. Weekly coaching calls continue. Monthly clinical calls continue. You keep optimizing.',
  },
  {
    q: 'What is the refund policy?',
    a: 'Six-month commitment. No refunds, no pause. This is for men who are ready to commit to their health optimization for at least six months. If you are not sure, join the free community first and take your time deciding.',
  },
  {
    q: 'Do I need to have previous bloodwork?',
    a: 'No. We order comprehensive labs for you regardless of whether you have had recent bloodwork. If you do have recent labs, bring them -- they give us a baseline. If you do not, we will get yours drawn within the first few weeks.',
  },
]

const PROCESS_STEPS = [
  {
    step: 'Step 1: Apply',
    description: 'Fill out your health history and goals. No discovery call. No "let\'s chat first." Your application is your intake. It takes about 5 minutes and it captures everything we need to know before you start. Submit the application, receive your payment link. Done.',
  },
  {
    step: 'Step 2: Labs',
    description: 'We order comprehensive bloodwork. Not the standard panel your doctor runs where they check cholesterol and blood sugar and call it a day. The full picture -- hormones, thyroid, metabolic markers, inflammatory markers, nutrient status. We need to see what is actually happening before we build anything.',
  },
  {
    step: 'Step 3: Clinical Review',
    description: 'Josh and the clinical team review your labs, build your protocol, and identify what actually needs to be optimized. You receive a full clinical report -- not a one-page summary. A detailed breakdown of every marker, what it means for your health, and what we are going to do about it. If your data supports HRT or prescription protocols, we facilitate a doctor referral. If it does not, we build your optimization plan without it.',
  },
  {
    step: 'Step 4: Coaching Active',
    description: 'Your dedicated fitness coach (Quinten) starts weekly calls covering training, nutrition, and recovery. Monthly clinical protocol calls with Josh where we review your data, adjust your plan, and make sure everything is moving in the right direction. Quarterly labs to measure progress and recalibrate. This is ongoing optimization, not a one-time program.',
  },
]

const TEAM = [
  {
    name: 'Josh Holyfield',
    role: 'Clinical Protocols & Program Direction',
    description: 'Clinical protocol design, monthly calls, lab interpretation, and overall program direction. Josh reviews every single client\'s bloodwork, builds the clinical protocol, and makes the call on whether referrals are needed. He is on your team for the full six months and beyond.',
  },
  {
    name: 'Quinten',
    role: 'Men\'s Fitness Coaching',
    description: 'Dedicated fitness coach for men\'s clients. Weekly calls covering training programming, nutrition planning, recovery optimization, and accountability. Quinten builds your training plan, adjusts it based on your progress and your labs, and makes sure you are actually executing on what the clinical protocol recommends.',
  },
  {
    name: 'Clinical Review Team',
    role: 'AI-Powered Lab Analysis',
    description: 'Your labs get a full clinical report generated by FRIDAY (AI-powered analysis) and reviewed by Josh. This is not a 5-minute doctor\'s glance at your bloodwork. It is a comprehensive breakdown of every marker, what it means, what to do about it, and how it connects to your training and nutrition plan.',
  },
]

const GHL_CALENDAR_URL = import.meta.env.VITE_GHL_CALENDAR_URL || ''

export default function Coaching() {
  return (
    <>
      <Helmet>
        <title>Iron Forge Brotherhood -- Health Optimization Coaching | $5,000 / 6 Months</title>
        <meta
          name="description"
          content="Health optimization coaching for men. Labs, clinical protocols, dedicated fitness coach, monthly calls with Josh. $5,000 for 6 months. No discovery call. Apply when you are ready."
        />
      </Helmet>

      {/* Section 1: Hero */}
      <Hero
        title="Health Optimization Coaching Built Around Your Bloodwork"
        subtitle="Labs. Protocols. Coaching. One system built around your data, not generic templates."
        ctaText="Apply Now"
        ctaHref="/apply"
      />

      {/* Section 2: The Problem */}
      <Section gradient="top">
        <div className="max-w-3xl mx-auto">
          <p className="text-text-secondary leading-relaxed mb-6">
            You are training harder than most people you know and you still feel like something is off because you have never actually looked at what is happening inside your body. You take supplements because someone on the internet said they work. You eat well because you have a general sense of what good nutrition looks like. You train consistently because you know that matters. And yet you are still guessing at whether any of it is actually optimized for your specific biology.
          </p>
          <p className="text-text-secondary leading-relaxed mb-6">
            That is not a discipline problem. That is a data problem. You do not know what your testosterone actually is. You do not know where your thyroid sits. You do not know if your cortisol is tanking your recovery. You do not know if the supplements you are taking are doing anything measurable. And without that data, every decision you make about your health is a guess dressed up as a plan.
          </p>
          <p className="text-text-secondary leading-relaxed">
            Most guys stay in that loop for years because they never run the labs, or they run basic labs through their primary care doctor who looks at the results, says everything is normal, and sends them home. Normal is not optimal. Normal is not what you are here for.
          </p>
        </div>
      </Section>

      {/* Section 3: How This Works */}
      <Section>
        <div className="max-w-3xl mx-auto">
          <h2 className="font-display text-3xl font-bold text-text-primary mb-10 text-center">
            How This Works
          </h2>
          <div className="space-y-10">
            {PROCESS_STEPS.map((item, i) => (
              <div key={i} className="flex gap-6">
                <div className="flex-shrink-0 w-10 h-10 rounded-full bg-brand-500 flex items-center justify-center text-white font-bold text-lg">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <h3 className="font-display text-lg font-bold text-text-primary mb-2">
                    {item.step}
                  </h3>
                  <p className="text-text-secondary leading-relaxed">
                    {item.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </Section>

      {/* Section 4: What's Included + Pricing Block */}
      <Section gradient="top">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-display text-3xl font-bold text-text-primary mb-6">
            What's Included
          </h2>
          <p className="text-text-secondary leading-relaxed mb-8">
            I am putting the price right here because I do not believe in hiding it behind a phone call. You should know what something costs before you decide if it is worth your time to learn more about it.
          </p>

          {/* Pricing Block (FUNNEL-SPEC verbatim) */}
          <div className="bg-surface-elevated border-l-4 border-brand-500 rounded-r-lg p-8 mb-8">
            <p className="font-display text-3xl font-bold text-text-primary mb-6">
              $5,000 — 6-month commitment
            </p>
            <p className="text-text-primary font-medium mb-4">Your team:</p>
            <ul className="space-y-3 mb-6">
              <li className="flex items-start gap-3">
                <svg className="w-5 h-5 text-brand-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-text-secondary">Dedicated fitness coach (weekly calls)</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-5 h-5 text-brand-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-text-secondary">Clinical protocol manager (monthly calls with Josh)</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-5 h-5 text-brand-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-text-secondary">AI-powered lab analysis and clinical reporting</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-5 h-5 text-brand-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-text-secondary">Quarterly bloodwork review and protocol optimization</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-5 h-5 text-brand-500 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-text-secondary">Doctor referral and prescription coordination when needed</span>
              </li>
            </ul>
            <p className="text-text-primary font-medium mb-4">
              After 6 months: $750/mo to continue
            </p>
            <p className="text-text-muted text-sm">
              Supplements, peptides, and prescriptions purchased separately as needed.
            </p>
            <p className="text-text-muted text-sm">
              Your team recommends. You decide.
            </p>
          </div>

          <p className="text-text-secondary leading-relaxed">
            That is the full cost. There is no enrollment fee on top of this. There is no "premium tier" that costs more. There is no add-on for lab analysis or clinical reports. The $5,000 covers six months of coached health optimization -- your training, your nutrition, your protocols, your bloodwork, your clinical calls, all of it. After six months, if you want to continue, it is $750 per month for the same level of service.
          </p>
        </div>
      </Section>

      {/* Section 5: The Team */}
      <Section>
        <h2 className="font-display text-3xl font-bold text-text-primary mb-10 text-center">
          The Team
        </h2>
        <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
          {TEAM.map((member) => (
            <div
              key={member.name}
              className="bg-surface-elevated rounded-xl p-6 border border-border"
            >
              <div className="w-16 h-16 rounded-full bg-surface-overlay border border-border flex items-center justify-center mb-4">
                <span className="text-2xl font-bold text-brand-400">
                  {member.name.charAt(0)}
                </span>
              </div>
              <h3 className="font-display text-lg font-bold text-text-primary">
                {member.name}
              </h3>
              <p className="text-brand-400 text-sm mt-1">{member.role}</p>
              <p className="text-text-secondary text-sm leading-relaxed mt-4">
                {member.description}
              </p>
            </div>
          ))}
        </div>
      </Section>

      {/* Section 6: Transparent Pricing */}
      <Section gradient="top">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-display text-3xl font-bold text-text-primary mb-6">
            Transparent Pricing
          </h2>
          <p className="text-text-secondary leading-relaxed mb-6">
            $5,000 for six months. $750 per month to continue after that.
          </p>
          <p className="text-text-secondary leading-relaxed mb-6">
            Products are separate. Anvil supplements are available at anvilnutrition.us if your protocol calls for them. If clinical review determines you would benefit from prescriptions (TRT, HRT, peptides), we facilitate a doctor referral -- that is separate billing through the medical provider. We coordinate everything. You decide what you want to use.
          </p>
          <p className="text-text-secondary leading-relaxed">
            No hidden fees. No add-ons. No "discovery call to find out pricing." It is $5,000 and you know exactly what you are getting before you ever talk to anyone on the team. The first real conversation is your first coaching call.
          </p>
        </div>
      </Section>

      {/* Section 7: FAQ */}
      <Section>
        <h2 className="font-display text-3xl font-bold text-text-primary mb-8 text-center">
          Frequently Asked Questions
        </h2>
        <FAQ items={COACHING_FAQ} />
      </Section>

      {/* Section 8: GHL Calendar Widget Embed */}
      {GHL_CALENDAR_URL && (
        <Section gradient="top">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="font-display text-3xl font-bold text-text-primary mb-4">
              Schedule a Call
            </h2>
            <p className="text-text-secondary mb-8">
              Not sure if this is right for you? Book a free 15-minute call to talk through your goals.
            </p>
            <div className="rounded-xl overflow-hidden border border-border">
              <iframe
                src={GHL_CALENDAR_URL}
                style={{ width: '100%', height: '700px', border: 'none' }}
                title="Book a Call"
              />
            </div>
          </div>
        </Section>
      )}

      {/* Section 9: CTA Block */}
      <Section>
        <CTABlock
          heading="Ready to stop guessing and start optimizing?"
          description="Not ready yet? Join the free community and learn at your own pace."
          primaryText="Apply for Coaching"
          primaryHref="/apply"
          secondaryText="Join the Brotherhood"
          secondaryHref={SKOOL_URL}
        />
      </Section>
    </>
  )
}
